[treesearch]
num_draft_nodes = 3
debug_prob = 0.3
epsilon = 0.3
max_iterations = 10

[exec]
timeout = 3600
workspace = "./workspace"

[agent]
k_fold_validation = 1

[agent.code]
model = "gpt-5.4"
model_temp = 1.0
